//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: drip_token
// ----------------------------------------------------------------------------
pub mod drip_token {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for drip_token
    pub fn program_id() -> Pubkey {
        pubkey!("9vXiabzy5j6UujwQGb7tPwviA9B1GDBpmKnnsFWu5zSs")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Claim
    // ....................................................................

    /// Main instruction struct for Claim
    pub struct ClaimInstruction {
        pub accounts: ClaimInstructionAccountMetas,
        pub data: ClaimInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Claim instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub user_state: AccountMeta,

        pub user_token_account: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,
    }

    /// Account pubkeys for Claim instruction
    #[derive(Debug, Clone)]
    pub struct ClaimInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub user_state: Pubkey,

        pub user_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl ClaimInstructionAccounts {
        pub fn new(
            user: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            user_state: Pubkey,

            user_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                user,

                config,

                mint,

                vault,

                user_state,

                user_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Claim
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimInstructionData {}

    impl ClaimInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimInstruction
    impl ClaimInstruction {
        fn discriminator() -> [u8; 8] {
            [62u8, 198u8, 214u8, 193u8, 213u8, 159u8, 108u8, 210u8]
        }

        pub fn data(data: ClaimInstructionData) -> Self {
            Self {
                accounts: ClaimInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.user_state = AccountMeta::new(accounts.user_state, false);

            self.accounts.user_token_account = AccountMeta::new(accounts.user_token_account, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.user_state.clone());

            metas.push(self.accounts.user_token_account.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseUserState
    // ....................................................................

    /// Main instruction struct for CloseUserState
    pub struct CloseUserStateInstruction {
        pub accounts: CloseUserStateInstructionAccountMetas,
        pub data: CloseUserStateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseUserState instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseUserStateInstructionAccountMetas {
        pub user: AccountMeta,

        pub config: AccountMeta,

        pub user_state: AccountMeta,
    }

    /// Account pubkeys for CloseUserState instruction
    #[derive(Debug, Clone)]
    pub struct CloseUserStateInstructionAccounts {
        pub user: Pubkey,

        pub config: Pubkey,

        pub user_state: Pubkey,
    }

    impl CloseUserStateInstructionAccounts {
        pub fn new(user: Pubkey, config: Pubkey, user_state: Pubkey) -> Self {
            Self {
                user,

                config,

                user_state,
            }
        }
    }

    /// Instruction data for CloseUserState
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseUserStateInstructionData {}

    impl CloseUserStateInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseUserStateInstruction
    impl CloseUserStateInstruction {
        fn discriminator() -> [u8; 8] {
            [127u8, 206u8, 172u8, 187u8, 146u8, 179u8, 215u8, 194u8]
        }

        pub fn data(data: CloseUserStateInstructionData) -> Self {
            Self {
                accounts: CloseUserStateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseUserStateInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.user_state = AccountMeta::new(accounts.user_state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.user_state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub claim_amount: u64,

        pub cooldown_seconds: u64,

        pub daily_limit: u64,

        pub mint: Pubkey,

        pub mode: u8,
    }

    impl InitializeInstructionData {
        pub fn new(
            claim_amount: u64,

            cooldown_seconds: u64,

            daily_limit: u64,

            mint: Pubkey,

            mode: u8,
        ) -> Self {
            Self {
                claim_amount,

                cooldown_seconds,

                daily_limit,

                mint,

                mode,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintToVault
    // ....................................................................

    /// Main instruction struct for MintToVault
    pub struct MintToVaultInstruction {
        pub accounts: MintToVaultInstructionAccountMetas,
        pub data: MintToVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintToVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintToVaultInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,
    }

    /// Account pubkeys for MintToVault instruction
    #[derive(Debug, Clone)]
    pub struct MintToVaultInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub token_program: Pubkey,
    }

    impl MintToVaultInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                mint,

                vault,

                token_program,
            }
        }
    }

    /// Instruction data for MintToVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintToVaultInstructionData {
        pub amount: u64,
    }

    impl MintToVaultInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintToVaultInstruction
    impl MintToVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [197u8, 102u8, 31u8, 8u8, 93u8, 20u8, 64u8, 185u8]
        }

        pub fn data(data: MintToVaultInstructionData) -> Self {
            Self {
                accounts: MintToVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintToVaultInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetVault
    // ....................................................................

    /// Main instruction struct for SetVault
    pub struct SetVaultInstruction {
        pub accounts: SetVaultInstructionAccountMetas,
        pub data: SetVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetVaultInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,

        pub vault: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for SetVault instruction
    #[derive(Debug, Clone)]
    pub struct SetVaultInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,

        pub vault: Pubkey,
    }

    impl SetVaultInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey, vault: Pubkey) -> Self {
            Self {
                config,

                admin,

                vault,
            }
        }
    }

    /// Instruction data for SetVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetVaultInstructionData {}

    impl SetVaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetVaultInstruction
    impl SetVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [177u8, 23u8, 187u8, 59u8, 247u8, 215u8, 255u8, 162u8]
        }

        pub fn data(data: SetVaultInstructionData) -> Self {
            Self {
                accounts: SetVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetVaultInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.vault = AccountMeta::new_readonly(accounts.vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateConfig
    // ....................................................................

    /// Main instruction struct for UpdateConfig
    pub struct UpdateConfigInstruction {
        pub accounts: UpdateConfigInstructionAccountMetas,
        pub data: UpdateConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateConfigInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for UpdateConfig instruction
    #[derive(Debug, Clone)]
    pub struct UpdateConfigInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl UpdateConfigInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for UpdateConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateConfigInstructionData {
        pub claim_amount: u64,

        pub cooldown_seconds: u64,

        pub daily_limit: u64,

        pub mode: u8,

        pub paused: bool,

        pub new_admin: Pubkey,
    }

    impl UpdateConfigInstructionData {
        pub fn new(
            claim_amount: u64,

            cooldown_seconds: u64,

            daily_limit: u64,

            mode: u8,

            paused: bool,

            new_admin: Pubkey,
        ) -> Self {
            Self {
                claim_amount,

                cooldown_seconds,

                daily_limit,

                mode,

                paused,

                new_admin,
            }
        }
    }

    /// Implementation for UpdateConfigInstruction
    impl UpdateConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [29u8, 158u8, 252u8, 191u8, 10u8, 83u8, 219u8, 99u8]
        }

        pub fn data(data: UpdateConfigInstructionData) -> Self {
            Self {
                accounts: UpdateConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateConfigInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: ClaimEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ClaimEvent {
    pub user: Pubkey,

    pub amount: u64,

    pub timestamp: i64,

    pub mode: u8,
}

impl ClaimEvent {
    pub fn new(user: Pubkey, amount: u64, timestamp: i64, mode: u8) -> Self {
        Self {
            user,

            amount,

            timestamp,

            mode,
        }
    }
}

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub admin: Pubkey,

    pub mint: Pubkey,

    pub vault: Pubkey,

    pub claim_amount: u64,

    pub cooldown_seconds: u64,

    pub daily_limit: u64,

    pub mode: u8,

    pub paused: bool,

    pub bump: u8,
}

impl Config {
    pub fn new(
        admin: Pubkey,

        mint: Pubkey,

        vault: Pubkey,

        claim_amount: u64,

        cooldown_seconds: u64,

        daily_limit: u64,

        mode: u8,

        paused: bool,

        bump: u8,
    ) -> Self {
        Self {
            admin,

            mint,

            vault,

            claim_amount,

            cooldown_seconds,

            daily_limit,

            mode,

            paused,

            bump,
        }
    }
}

/// Custom struct: UserState
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UserState {
    pub last_claim_ts: i64,

    pub claimed_today: u64,

    pub last_day_ts: i64,

    pub bump: u8,
}

impl UserState {
    pub fn new(last_claim_ts: i64, claimed_today: u64, last_day_ts: i64, bump: u8) -> Self {
        Self {
            last_claim_ts,

            claimed_today,

            last_day_ts,

            bump,
        }
    }
}

/// Custom struct: UserStateClosed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UserStateClosed {
    pub user: Pubkey,

    pub timestamp: i64,
}

impl UserStateClosed {
    pub fn new(user: Pubkey, timestamp: i64) -> Self {
        Self { user, timestamp }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
